<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<OutputType>WinExe</OutputType>
		<LangVersion>14.0</LangVersion>
		<TargetFramework>Net10.0-Windows10.0.22621.0</TargetFramework>
		<Nullable>Enable</Nullable>
		<ImplicitUsings>Enable</ImplicitUsings>
		<UseWPF>True</UseWPF>
		<UseWindowsForms>False</UseWindowsForms>
		<ApplicationIcon>Images\Ico.ico</ApplicationIcon>
		<BaseOutputPath>Binary\</BaseOutputPath>
		<SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
	</PropertyGroup>

	<ItemGroup>
		<Using Include="OpenCvSharp.Point">
			<Alias>Point</Alias>
		</Using>
		<Using Include="OpenCvSharp.Rect">
			<Alias>Rect</Alias>
		</Using>
		<Using Include="OpenCvSharp.Size">
			<Alias>Size</Alias>
		</Using>
		<Using Include="SixLabors.ImageSharp.Image">
			<Alias>Image</Alias>
		</Using>
	</ItemGroup>

	<ItemGroup>
		<None Remove="Images\Ico.ico" />
		<None Remove="Images\BuildImg.png" />
		<None Remove="Images\EvalnImg.png" />
		<None Remove="Images\FilesImg.png" />
		<None Remove="Images\ModelImg.png" />
		<None Remove="Images\PhotoImg.png" />
		<None Remove="Images\VideoImg.png" />
	</ItemGroup>
	<ItemGroup>
		<Resource Include="Images\Ico.ico" />
		<Resource Include="Images\BuildImg.png" />
		<Resource Include="Images\EvalnImg.png" />
		<Resource Include="Images\FilesImg.png" />
		<Resource Include="Images\ModelImg.png" />
		<Resource Include="Images\PhotoImg.png" />
		<Resource Include="Images\VideoImg.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="OpenCvSharp4.WpfExtensions" Version="4.11.0.20250507" />
		<PackageReference Include="EPPlus" Version="8.3.0" />
		<PackageReference Include="ScottPlot.WPF" Version="5.1.57" />
		<PackageReference Include="YoloSharp.Core" Version="6.0.6" />
		<PackageReference Include="Extended.Wpf.Toolkit" Version="5.0.0" />
		<PackageReference Include="MaterialDesignThemes" Version="5.3.0" />
		<PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
		<PackageReference Include="OpenCvSharp4.Windows" Version="4.11.0.20250507" />
		<PackageReference Include="Microsoft.ML.OnnxRuntime.Gpu.Windows" Version="1.23.2" />
	</ItemGroup>

</Project>