global using Compunet.YoloSharp;
global using Microsoft.Win32;
global using SewerDeformationSoftware.Logics.Shareds;
global using SewerDeformationSoftware.Views;
global using System.ComponentModel;
global using System.Globalization;
global using System.IO;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Data;
global using System.Windows.Input;
global using System.Windows.Interop;
global using System.Windows.Media;
global using System.Windows.Threading;
global using MessageBox = Xceed.Wpf.Toolkit.MessageBox;